### ISSUE TITLE
Issue with reward_metrics dictionary

### ISSUE THREAD

**Issue by SSubhnil** [zoharri/mamba#1]
I think the reward_metrics dictionary in models.py (line 465) is not defined anywhere before being declared in the 'for' loop. I am also struggling to find any reference to anything similar to this dictionary.

Let me know what you think!

**Comment by zoharri** [comment]
Hi @SSubhnil,  thank you for bringing this to my attention. You are right, this dictionary is a leftover from a deleted code chunk. 
I pushed a fix, let me know if you have any further problems.
